# Reference: https://longhorn.io/docs/1.11.1/advanced-resources/os-distro-specific/csi-on-k3s/
- name: Install requirements for longhorn
  hosts:
    - hive-proxmox
    - hive02-proxmox
    - mh-frame01
  vars_files:
    - ../vars/credentials.yml
  tasks:
    - name: Install open-iscsi
      ansible.builtin.package:
        name: open-iscsi
        state: present
      become: true
